apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
spec:
  rules:
  - host: auth.mint.mosorio.dev
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 8080
